version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public   # Mount public folder for static assets (like data.csv)
    environment:
      - NODE_ENV=production